### ISSUE TITLE
Record previous searches

### ISSUE THREAD

**Issue by khattakdev** [MLH-Fellowship/prep-project-4.1.1#12]
Add a search log somewhere on the page that shows the last 3 - 5 search logs, including the weather (at the time of search).
Something like the following:

- New York 17.36°C, (Tues) 12 Oct 2021
- Delhi 30°C, (Tues) 12 Oct 2021
- New York 12.36°C, (Tues) 12 Oct 2021

You can save this data in the local storage, you don't need to make an actual Database

**Comment by khattakdev** [comment]
@Tanmay000009 I think the easy solution/fix for this would be to add a search icon, on clicking that, an API call will be made. This way you won't be making unnecessary calls. You can also make that it makes an API call when the user taps the **Return** key.

**Comment by Tanmay000009** [comment]
> @Tanmay000009 I think the easy solution/fix for this would be to add a search icon, on clicking that, an API call will be made. This way you won't be making unnecessary calls. You can also make that it makes an API call when the user taps the **Return** key.

Sure thing. Thank you so much for helping, we'll go with the issue as you said!
