### ISSUE TITLE
Graph of weather forecast

### ISSUE THREAD

**Issue by atharmohammad** [MLH-Fellowship/prep-project-4.1.1#9]
We can show a graph of weather forecast to user for upcoming 10 days for a particular location

Edit : its for upcoming 7 days

- We can also show weather for past 5 days ,so user can see how weather is changing if this is something looks reasonable for user to know  (would appericiate other people views on this one)

**Comment by ShiviPro** [comment]
I don't have any idea about 10 days, but we can get a daily forecast of upto 7 days with free plan of OpenWeather's One Call API.
Also Chart.js can be considered as an viable option to provide graphical representation here.

This one seems very interesting @atharmohammad. Can I work with you on this, in case you get this assigned ?

**Comment by atharmohammad** [comment]
> I don't have any idea about 10 days, but we can get a daily forecast of upto 7 days with free plan of OpenWeather's One Call API. Also Chart.js can be considered as a viable option to provide graphical representation here.
> 
> This one seems very interesting @atharmohammad. Can I work with you on this, in case you get this assigned ?

Yes you are correct we can forecast daily for 7 days , maybe we can also show weather of past 5 days. Let's first see if this could be accomplish , it's open for discussion . sure if issue gets approved , we can work on it , some other can also join us untill more issue gets opened 👍
